"""Baseline schema.

Frozen, explicit DDL for the whole schema. This migration is intentionally NOT derived
from ``Base.metadata`` at runtime: a baseline that calls ``create_all`` mutates whenever
the models change, so the first ordinary migration added on top would fail on every fresh
database (the baseline would already have created the new column). Everything here is
static ``op.create_table`` / ``op.create_index`` DDL.

Consolidated baseline: this single revision reflects the complete current schema - core
knowledge/permission tables plus the connector/entity/verification/SSO/SCIM feature set and
all performance indexes. Subsequent schema changes are ordinary autogenerated migrations
layered on top. The public pre-launch ``waitlist_entries`` table (formerly revision
0002_waitlist) and the ``device_authorizations`` table (formerly revision 0002_device_auth)
were squashed into this baseline for the initial public release. A database migrated from a
pre-release checkout must be wiped, or stamped to this baseline with
``alembic stamp 0001_initial`` if its schema already matches.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01 00:00:00
"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from app.core.config import settings


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector must exist before the Vector column / HNSW index are created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='plantier', native_enum=False, length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_entries_created', 'waitlist_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=True)
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_table('access_grants',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('COLLECTION', 'DOCUMENT', name='resourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('principal_type', sa.Enum('USER', 'TEAM', name='principaltype', native_enum=False, length=32), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('NONE', 'VIEWER', 'EDITOR', 'MANAGER', name='permissionlevel', native_enum=False, length=32), nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=True),
    # Data-source linkage (source-synced ACLs). FK added after ``data_sources`` exists.
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'principal_type', 'principal_id', name='uq_grant_resource_principal')
    )
    op.create_index(op.f('ix_access_grants_id'), 'access_grants', ['id'], unique=False)
    op.create_index(op.f('ix_access_grants_org_id'), 'access_grants', ['org_id'], unique=False)
    op.create_index(op.f('ix_access_grants_source_id'), 'access_grants', ['source_id'], unique=False)
    op.create_index('ix_grant_lookup', 'access_grants', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_grant_principal', 'access_grants', ['principal_type', 'principal_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('acts_as_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acts_as_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('connectors',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('OPENAI', 'AZURE_OPENAI', 'OLLAMA', 'CUSTOM', name='connectortype', native_enum=False, length=32), nullable=False),
    sa.Column('purpose', sa.Enum('EMBEDDING', 'COMPLETION', name='connectorpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_credentials', sa.String(length=4096), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.create_index(op.f('ix_connectors_org_id'), 'connectors', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='orgrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', name='membershipstatus', native_enum=False, length=32), nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('parent_team_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_team_id'], ['teams.id'], ondelete='SET NULL', name='fk_teams_parent_team_id_teams'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_team_org_slug')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_index(op.f('ix_teams_parent_team_id'), 'teams', ['parent_team_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_api_key_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_org_time', 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.create_table('collections',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('owner_team_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'ORG', 'PUBLIC', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('default_permission', sa.Enum('NONE', 'VIEWER', 'EDITOR', 'MANAGER', name='permissionlevel', native_enum=False, length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_collection_org_slug')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_org_id'), 'collections', ['org_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('LEAD', 'MEMBER', name='teamrole', native_enum=False, length=32), server_default='MEMBER', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('EMBEDDING', 'COMPLETION', 'SEARCH', 'INGEST', name='usagekind', native_enum=False, length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_org_kind_time', 'usage_records', ['org_id', 'kind', 'created_at'], unique=False)
    op.create_index('ix_usage_org_time', 'usage_records', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_org_id'), 'usage_records', ['org_id'], unique=False)
    op.create_table('documents',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.Enum('FILE', 'TEXT', 'URL', 'CONNECTOR', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'ORG', 'PUBLIC', name='visibility', native_enum=False, length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', 'QUARANTINED', 'ARCHIVED', name='documentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    # Verified answers / content freshness (feature: verification). ``server_default`` mirrors
    # the value the ORM writes so raw inserts are also safe.
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'STALE', name='verificationstatus', native_enum=False, length=16), server_default='UNVERIFIED', nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    # DLP classification (feature: PII/DLP). NONE unless the sensitivity scan hit.
    sa.Column('sensitivity', sa.Enum('NONE', 'PII', 'CONFIDENTIAL', name='sensitivitylevel', native_enum=False, length=16), server_default='NONE', nullable=False),
    # Data-source linkage (feature: connectors). FK added after ``data_sources`` exists.
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL', name='fk_documents_verified_by_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_index(op.f('ix_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_sensitivity'), 'documents', ['sensitivity'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_verification_status'), 'documents', ['verification_status'], unique=False)
    op.create_index(
        'uq_documents_source_external', 'documents', ['source_id', 'external_id'],
        unique=True, postgresql_where=sa.text('source_id IS NOT NULL'),
    )
    op.create_table('document_chunks',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    # Dimension is driven by EMBEDDING_DIM (matching models.chunk.DocumentChunk.embedding) so
    # a non-default embedding model produces a schema that actually accepts its vectors. The
    # default is 1536 (text-embedding-3-small). Changing it requires a fresh DB or a manual
    # ``ALTER TABLE ... TYPE vector(N)`` + HNSW rebuild.
    sa.Column('embedding', Vector(settings.EMBEDDING_DIM), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_collection_id'), 'document_chunks', ['collection_id'], unique=False)
    op.create_index('ix_document_chunks_doc_order', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_document_chunks_org_id'), 'document_chunks', ['org_id'], unique=False)

    # Full-text keyword-search index for hybrid retrieval. This is a functional expression
    # index that cannot be declared on the model, so it is created explicitly here.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_chunks_content_fts "
        "ON document_chunks USING gin (to_tsvector('english', content))"
    )

    op.create_table('conversations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('collection_ids', sa.JSON(), nullable=True),
    sa.Column('web_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_org_id'), 'conversations', ['org_id'], unique=False)
    op.create_index('ix_conversations_org_user', 'conversations', ['org_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PERSON', 'ORG', 'PRODUCT', 'PROJECT', 'LOCATION', 'OTHER', name='entitykind', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized', sa.String(length=512), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'kind', 'normalized', name='uq_entity_org_kind_norm')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_org_id'), 'entities', ['org_id'], unique=False)
    op.create_index('ix_entities_org_kind', 'entities', ['org_id', 'kind'], unique=False)
    op.create_index('ix_entities_org_normalized', 'entities', ['org_id', 'normalized'], unique=False)
    op.create_table('invites',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='orgrole', native_enum=False, length=32), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_token', sa.String(length=64), nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitestatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_invite_org_email')
    )
    op.create_index(op.f('ix_invites_hashed_token'), 'invites', ['hashed_token'], unique=True)
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_index(op.f('ix_invites_org_id'), 'invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_invites_token_prefix'), 'invites', ['token_prefix'], unique=False)
    op.create_table('query_insights',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('SEARCH', 'CHAT', name='querykind', native_enum=False, length=16), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Enum('UP', 'DOWN', name='feedbackrating', native_enum=False, length=8), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_insights_id'), 'query_insights', ['id'], unique=False)
    op.create_index('ix_query_insights_org_created', 'query_insights', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_insights_org_id'), 'query_insights', ['org_id'], unique=False)
    op.create_index('ix_query_insights_org_rating', 'query_insights', ['org_id', 'rating'], unique=False)
    op.create_table('scim_tokens',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_token', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scim_tokens_hashed_token'), 'scim_tokens', ['hashed_token'], unique=True)
    op.create_index(op.f('ix_scim_tokens_id'), 'scim_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_scim_tokens_org_id'), 'scim_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_scim_tokens_token_prefix'), 'scim_tokens', ['token_prefix'], unique=False)
    op.create_table('sso_connections',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.Enum('OIDC', 'SAML', name='ssoprotocol', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=8192), nullable=True),
    sa.Column('default_role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='orgrole', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_sso_connection_org_name')
    )
    op.create_index('ix_sso_connections_domain', 'sso_connections', ['email_domain'], unique=False)
    op.create_index(op.f('ix_sso_connections_id'), 'sso_connections', ['id'], unique=False)
    op.create_index(op.f('ix_sso_connections_org_id'), 'sso_connections', ['org_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_messages_conv_seq', 'conversation_messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_org_id'), 'conversation_messages', ['org_id'], unique=False)
    op.create_table('external_identities',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.Enum('USER', 'GROUP', name='externalprincipalkind', native_enum=False, length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name='uq_external_identity')
    )
    op.create_index(op.f('ix_external_identities_id'), 'external_identities', ['id'], unique=False)
    op.create_index(op.f('ix_external_identities_org_id'), 'external_identities', ['org_id'], unique=False)
    op.create_index(op.f('ix_external_identities_team_id'), 'external_identities', ['team_id'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_index('ix_external_identity_lookup', 'external_identities', ['provider', 'external_id'], unique=False)
    op.create_table('federated_identities',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['sso_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_federated_identity')
    )
    op.create_index(op.f('ix_federated_identities_id'), 'federated_identities', ['id'], unique=False)
    op.create_index(op.f('ix_federated_identities_org_id'), 'federated_identities', ['org_id'], unique=False)
    op.create_index(op.f('ix_federated_identities_user_id'), 'federated_identities', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'ORG', 'PUBLIC', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'STALE', name='verificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_collection_id'), 'answers', ['collection_id'], unique=False)
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_index(op.f('ix_answers_org_id'), 'answers', ['org_id'], unique=False)
    op.create_index('ix_answers_org_status', 'answers', ['org_id', 'verification_status'], unique=False)
    op.create_table('data_sources',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('LOCAL_FOLDER', 'GOOGLE_DRIVE', 'SLACK', 'GITHUB', 'NOTION', 'CONFLUENCE', name='datasourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SYNCING', 'ERROR', name='datasourcestatus', native_enum=False, length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=8192), nullable=True),
    sa.Column('cursor', sa.String(length=2048), nullable=True),
    sa.Column('default_visibility', sa.Enum('PRIVATE', 'TEAM', 'ORG', 'PUBLIC', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_data_source_org_name')
    )
    op.create_index(op.f('ix_data_sources_collection_id'), 'data_sources', ['collection_id'], unique=False)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_org_id'), 'data_sources', ['org_id'], unique=False)
    op.create_index('ix_data_sources_org_status', 'data_sources', ['org_id', 'status'], unique=False)
    op.create_table('document_entities',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entity_id', name='uq_document_entity')
    )
    op.create_index(op.f('ix_document_entities_document_id'), 'document_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_entities_entity_id'), 'document_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_entities_id'), 'document_entities', ['id'], unique=False)
    op.create_index(op.f('ix_document_entities_org_id'), 'document_entities', ['org_id'], unique=False)
    op.create_table('document_external_principals',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.Enum('USER', 'GROUP', name='externalprincipalkind', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'provider', 'external_id', name='uq_doc_external_principal')
    )
    op.create_index('ix_doc_ext_principal_lookup', 'document_external_principals', ['provider', 'external_id'], unique=False)
    op.create_index(op.f('ix_document_external_principals_document_id'), 'document_external_principals', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_external_principals_id'), 'document_external_principals', ['id'], unique=False)
    op.create_index(op.f('ix_document_external_principals_org_id'), 'document_external_principals', ['org_id'], unique=False)
    op.create_index(op.f('ix_document_external_principals_source_id'), 'document_external_principals', ['source_id'], unique=False)

    # Cross-table FKs to ``data_sources`` (created last): added now that the target exists.
    op.create_foreign_key(
        'fk_access_grants_source_id_data_sources', 'access_grants', 'data_sources',
        ['source_id'], ['id'], ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_documents_source_id_data_sources', 'documents', 'data_sources',
        ['source_id'], ['id'], ondelete='CASCADE',
    )

    # Performance indexes for hot lookup/ordering paths.
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_index(
        'ix_documents_org_visibility', 'documents', ['org_id'],
        postgresql_where=sa.text('visibility IS NOT NULL'),
    )
    op.create_index('ix_documents_org_created', 'documents', ['org_id', sa.text('created_at DESC')])
    op.create_index('ix_documents_meta_file_token', 'documents', [sa.text("(metadata ->> 'file_token')")])
    op.create_index('ix_memberships_org_created', 'memberships', ['org_id', 'created_at'])

    # Device authorizations: CLI sign-in approved from the browser (the /device-auth flow).
    # Created last, after its FK targets (organizations, users, api_keys). The partial unique
    # index keeps ``user_code`` unambiguous only among PENDING rows.
    op.create_table(
        "device_authorizations",
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("user_code", sa.String(length=16), nullable=False),
        sa.Column("device_code_prefix", sa.String(length=16), nullable=False),
        sa.Column("hashed_device_code", sa.String(length=64), nullable=False),
        sa.Column("requested_scopes", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "DENIED",
                "EXPIRED",
                "CONSUMED",
                name="deviceauthstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("encrypted_secret", sa.String(length=8192), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_authorizations_device_code_prefix"),
        "device_authorizations",
        ["device_code_prefix"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_authorizations_hashed_device_code"),
        "device_authorizations",
        ["hashed_device_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_device_authorizations_id"), "device_authorizations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_device_authorizations_org_id"), "device_authorizations", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_authorizations_user_code"),
        "device_authorizations",
        ["user_code"],
        unique=False,
    )
    op.create_index(
        "uq_device_auth_user_code_pending",
        "device_authorizations",
        ["user_code"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )


def downgrade() -> None:
    # Device authorizations (folded in from 0002_device_auth): dropped first, before FK targets.
    op.drop_index("uq_device_auth_user_code_pending", table_name="device_authorizations")
    op.drop_index(op.f("ix_device_authorizations_user_code"), table_name="device_authorizations")
    op.drop_index(op.f("ix_device_authorizations_org_id"), table_name="device_authorizations")
    op.drop_index(op.f("ix_device_authorizations_id"), table_name="device_authorizations")
    op.drop_index(
        op.f("ix_device_authorizations_hashed_device_code"), table_name="device_authorizations"
    )
    op.drop_index(
        op.f("ix_device_authorizations_device_code_prefix"), table_name="device_authorizations"
    )
    op.drop_table("device_authorizations")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_content_fts")
    op.drop_index('ix_memberships_org_created', table_name='memberships')
    # if_exists: a DB stamped at this baseline BEFORE an index was folded in never ran the
    # create, so an unconditional drop would make downgrade fail on exactly those DBs (see
    # docs/DEPLOYMENT.md, "Upgrading a database stamped at an older baseline").
    op.drop_index('ix_documents_meta_file_token', table_name='documents', if_exists=True)
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.drop_index(
        'ix_documents_org_visibility', table_name='documents',
        postgresql_where=sa.text('visibility IS NOT NULL'),
    )
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_constraint('fk_documents_source_id_data_sources', 'documents', type_='foreignkey')
    op.drop_constraint('fk_access_grants_source_id_data_sources', 'access_grants', type_='foreignkey')
    op.drop_table('document_external_principals')
    op.drop_table('document_entities')
    op.drop_table('data_sources')
    op.drop_table('answers')
    op.drop_table('federated_identities')
    op.drop_table('external_identities')
    op.drop_table('conversation_messages')
    op.drop_table('sso_connections')
    op.drop_table('scim_tokens')
    op.drop_table('query_insights')
    op.drop_table('invites')
    op.drop_table('entities')
    op.drop_table('conversations')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    op.drop_table('usage_records')
    op.drop_table('team_members')
    op.drop_table('collections')
    op.drop_table('audit_logs')
    op.drop_table('teams')
    op.drop_table('memberships')
    op.drop_table('connectors')
    op.drop_table('api_keys')
    op.drop_table('access_grants')
    op.drop_table('waitlist_entries')
    op.drop_table('users')
    op.drop_table('organizations')
